sudo: false
language: node_js
node_js:
  - "5"
  - "6"
os:
  - 'osx'
  - 'linux'
addons:
  apt:
    packages:
      - xvfb
before_script:
  - "export DISPLAY=:99.0"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - sleep 3 # give xvfb some time to start
